// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoGk8DUd472fvqJd0sOiCjK2LRcytUQnk',
    appId: '1:377063955350:web:9d3cc2ead840201364dbb7',
    messagingSenderId: '377063955350',
    projectId: 'goinvest-90853',
    authDomain: 'goinvest-90853.firebaseapp.com',
    storageBucket: 'goinvest-90853.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkIQfsUDPInL9Wk2vsClfOASvYiAiwJeE',
    appId: '1:377063955350:android:ff1922bbbf100ff264dbb7',
    messagingSenderId: '377063955350',
    projectId: 'goinvest-90853',
    storageBucket: 'goinvest-90853.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-o3-WRC1jRzeGRs2xfrS_T-ijxYRdnOw',
    appId: '1:377063955350:ios:2f015c89944460a864dbb7',
    messagingSenderId: '377063955350',
    projectId: 'goinvest-90853',
    storageBucket: 'goinvest-90853.appspot.com',
    iosBundleId: 'com.example.goInvest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-o3-WRC1jRzeGRs2xfrS_T-ijxYRdnOw',
    appId: '1:377063955350:ios:2f015c89944460a864dbb7',
    messagingSenderId: '377063955350',
    projectId: 'goinvest-90853',
    storageBucket: 'goinvest-90853.appspot.com',
    iosBundleId: 'com.example.goInvest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoGk8DUd472fvqJd0sOiCjK2LRcytUQnk',
    appId: '1:377063955350:web:fad67026e30c5dba64dbb7',
    messagingSenderId: '377063955350',
    projectId: 'goinvest-90853',
    authDomain: 'goinvest-90853.firebaseapp.com',
    storageBucket: 'goinvest-90853.appspot.com',
  );

}